To common
INSAgenda/common pull request #1
Opened 2022-08-14 16:33 UTC by DimitriTimoz

2022-08-24 23:10 UTC, Mubelotix requested changes

2022-08-24 23:10 UTC, Mubelotix commented on src/password.rs
> +                "Le mot de passe doit être compris entre 10 et 128 caractères".to_string(),
```suggestion
                "Le mot de passe doit posséder entre 10 et 128 caractères".to_string(),
```

2022-08-24 23:10 UTC, Mubelotix commented on src/password.rs
> +                "Le mot de passe doit contenir au moins une lettre majuscule et une lettre minuscule".to_string(),
```suggestion
                "The password must contain at least one uppercase or lowercase letter".to_string(),
                "Le mot de passe doit contenir au moins une lettre majuscule ou minuscule".to_string(),
```

2022-08-24 23:10 UTC, Mubelotix commented on src/password.rs
> +    if errors.len() > 0 {
```suggestion
    if errors.len() > 1 {
```

2022-08-24 23:14 UTC, DimitriTimoz commented on src/password.rs
> +    if errors.len() > 0 {
bah pourquoi ?
Il ne va pas retourner une erreur seulement s'il y en a plus de 2 ? 
S'il y en a au moins une il faut la retourner.

2022-08-24 23:18 UTC, DimitriTimoz commented on src/password.rs
> +                "Le mot de passe doit contenir au moins une lettre majuscule et une lettre minuscule".to_string(),
l'erreur vient plutôt du nom de l'enum et pas de l'erreur

2022-08-24 23:20 UTC, Mubelotix commented on src/password.rs
> +    if errors.len() > 0 {
Non une c'est beaucoup trop chiant, même les recommandations de l'OWASP le disaient

2022-08-24 23:20 UTC, Mubelotix commented on src/password.rs
> +                "Le mot de passe doit contenir au moins une lettre majuscule et une lettre minuscule".to_string(),
Et bah change le nom de l'enum, on va pas retourner une erreur inexacte quand même

2022-08-24 23:21 UTC, Mubelotix commented on src/password.rs
> +                "Le mot de passe doit contenir au moins une lettre majuscule et une lettre minuscule".to_string(),
c'est pas assez clair

2022-08-24 23:23 UTC, DimitriTimoz commented on src/password.rs
> +    if errors.len() > 0 {
À ce moment là il faut pas appliquer la règle sur tout sinon si l'utilisateur met 4 caractères sont mdp serait accepté

2022-08-24 23:23 UTC, DimitriTimoz commented on src/password.rs
> +                "Le mot de passe doit contenir au moins une lettre majuscule et une lettre minuscule".to_string(),
j'ai rename l'enum

2022-08-26 14:21 UTC, Mubelotix approved these changes

2022-08-26 14:22 UTC, merged